### ISSUE TITLE
Multiple algorithms within same draft

### ISSUE THREAD

**Issue by jakemas** [lamps-wg/nist-pqc-kem-kyber-certificates#6]
When constructing the draft for PQ signature algorithms for X.509, I envisioned the draft to encompass all chosen signature algorithms from NISTs PQC project (e.g., say both Dilithium and SPHINCS+ are selected, then the draft would include both algorithms). However Panos has given a few reasons to restrict each draft to a single algorithm type (e.g. say, just Dilithium), and have multiple drafts.

The same question can be asked for the KEM algorithms chosen, say NIST select 3 to be standardised, would we combine all algorithms in the same draft? or split them separately. Currently this draft names multiple candidates.

Some reasons for separating:
- There may exist vast differences in mathematical underpinning (say between a lattice and a code-based candidate) - this would be like seeing ECDSA and RSA in the same draft.
- Should any algorithm become revoked/deprecated the separation would more cleanly provide the means to reflect this in the drafts with potentially less confusion to the reader.
- More algorithms in a single draft may bloat the specific security considerations (that may significantly vary if based upon different underpinning).
- May allow separate drafts to move fast through the IETF process.

Just opening a dialogue for rebuttal/discussion.

**Comment by seanturner** [comment]
These are all really good points and to be honest I really do not have a super strong reason to keep them all in one I-D.  This is definitely something that we can raise to the WG when reviewing the I-D.

One the point about deprecating algorithms more easily: I sure hope that won't happen anytime soon.

**Comment by bwesterb** [comment]
I hope it won't happen either, but it's not unlikely that some schemes will loose security due to advances in cryptanalysis. What I am sure of, is that we'll see new more performant signature schemes proposed in a few years.

**Comment by seanturner** [comment]
You have won me over to one alg per I-D. Helps that NIST just picked Kyber. Will get to modifying this I-D to reflect that in the text and in the name.
